export const items = [
    {
        id: Math.random(),
        title: "وجبة فطار",
        description: "  مافن ساخنة وبيض مخفوق طري وصوصج حلال ساخنة شهيّة، وكمّلها مع هاش براونز ذهبية مقرمشة.",
        price: "60 جنية",
        category: "فطار",
        imgUrl: "https://s7d1.scene7.com/is/image/mcdonalds/mcd-Big-Breakfast-uae:1-4-product-tile-desktop",
    },
    {
        id: Math.random(),
        title: "وجبة فطار",
        description: "مصدر رائع وشهي للبروتين الذي تحتاجه ليوم يملؤه النشاط. تأتي وجبة فطورنا الخاصة من بيضة عالية الجودة Grade A على مافن إنكليزي طازج مع زبدة وشريحة دجاج وجبنة أميركية ذائبة. يتكون كل ذلك من 290 سعرة حرارية.",
        price: "70 جنية",
        category: "فطار",
        imgUrl: "https://s7d1.scene7.com/is/image/mcdonalds/mcd-Egg-mcmuffin-uae:product-header-desktop?wid=829&hei=455&dpr=off",
    },
    {
        id: Math.random(),
        title: "وجبة فطار ممتازة",
        description: "بيض شهيّ مع هاش براونز المقرمش مغمورة بجبنة الشيدر الذائبة مع الدجاج وملفوفة بخبز التورتيلا.",
        price: "90 جنية",
        category: "فطار",
        imgUrl: "https://s7d1.scene7.com/is/image/mcdonalds/mcd-Egg-n-Hashbrown-wrap-uae:1-4-product-tile-desktop",
    },
    {
        id: Math.random(),
        title: "وجبة غداء",
        description: "قطعة دجاج حلال مقرمش مع المايونيز والخس المقطّع داخل الخبز المحمّص. وتُقدّم مع البطاطس الشهيرة عالمياً®، ومشروب بالحجم المتوسط من اختيارك.",
        price: "80 جنية",
        category: "غداء",
        imgUrl: "https://s7d1.scene7.com/is/image/mcdonalds/mcd-McChicken-new-uae:1-4-product-tile-desktop",
    },
    {
        id: Math.random(),
        title: "وجبة غداء درجة اولي",
        description: "أعِد شحن طاقتك مع كوارتر باوندر بالجبنة! تتكوّن من قطعة لحم البقر الحلال** يتم إعدادها فقط عند طلب وجبتك. وتُقدّم وجبة كوارتر باوندر بالجبنة مع البطاطس الشهيرة عالمياً®، ومشروب بالحجم المتوسط من اختيارك.",
        price: "90 جنية",
        category: "غداء",
        imgUrl: "https://s7d1.scene7.com/is/image/mcdonalds/mcd-QPC-meal-uae:1-4-product-tile-desktop",
    },
    {
        id: Math.random(),
        title: "وجبة غداء ممتازة",
        description: "بيج ماك® الفريدة والمكوّنة من قطعتي خبز برجر مع السمسم، وصلصة بيج ماك، والجبنة الأميركية، والمخلّل المقطّع. وتُقدّم وجبة بيج ماك® مع البطاطس الشهيرة عالمياً®، ومشروبك المفضّل من الكوكاكولا.",
        price: "50 جنية",
        category: "غداء",
        imgUrl: "https://s7d1.scene7.com/is/image/mcdonalds/mcd-Big-Mac-new-uae:1-4-product-tile-desktop",
    },
    {
        id: Math.random(),
        title: "وجبة عشاء",
        description: "طعم لا يُصدّق وسندويتش تأسر القلوب، قطعتين من الدجاج الحلال المغطّى بطبقة من البقسماط وجبنة وخس ومايونيز وقطعة خبز شهيّة في الوسط! هل جربتها بعد؟",
        price: "50 جنية",
        category: "عشاء",
        imgUrl: "https://s7d1.scene7.com/is/image/mcdonalds/mcd-Chicken-Mac-uae:product-header-desktop?wid=829&hei=455&dpr=off",
    },
    {
        id: Math.random(),
        title: "وجبة عشاء درجة اولي",
        description: "3 قطع اتشكن حار باعتدال",
        price: "50 جنية",
        category: "عشاء",
        imgUrl: "https://s7d1.scene7.com/is/image/mcdonalds/mcd-McWings-uae:1-4-product-tile-desktop",
    }
];